package com.csc205.project2;

import com.csc205.project2.Rhombohedron;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;
/* for Extra Credit: this Test class was generated by this prompt:
"write a test class called RhombohedronTest.java, that tests all the method's in the Rhombohedron.java class.write a test class called RhombohedronTest.java, that tests all the method's in the Rhombohedron.java class."

 */
public class RhombohedronTest {

    private Rhombohedron rhombohedron;

    @BeforeEach
    public void setUp() {
        rhombohedron = new Rhombohedron(5.0, 60);
    }

    @Test
    public void testGetEdgeLength() {
        assertEquals(5.0, rhombohedron.getEdgeLength());
    }

    @Test
    public void testSetEdgeLength() {
        rhombohedron.setEdgeLength(6.0);
        assertEquals(6.0, rhombohedron.getEdgeLength());
    }

    @Test
    public void testGetAngle() {
        assertEquals(Math.toRadians(60), rhombohedron.getAngle());
    }

    @Test
    public void testSetAngle() {
        /*AI doesn't know that Java likes radians*/
        rhombohedron.setAngle(70);
        assertEquals(70, Math.toDegrees(rhombohedron.getAngle()));
    }

    @Test
    public void testSurfaceArea() {
        // Assuming the surface area calculation is correct
        double expectedSurfaceArea = 6 * Math.pow(5.0, 2) * Math.sin(Math.toRadians(60));
        assertEquals(expectedSurfaceArea, rhombohedron.surfaceArea(), 0.0001);
    }

    @Test
    public void testVolume() {
        // Assuming the volume calculation is correct
        double expectedVolume =  Math.pow(5.0, 3) * Math.sqrt(1 - Math.pow(Math.cos(Math.toRadians(60)), 2));
        assertEquals(expectedVolume, rhombohedron.volume(), 0.0001);
    }

    @Test
    public void testToString() {
        String expected = String.format("Rhombohedron {edgeLength=%.2f, angle=%.2f, surface area=%.2f, volume=%.2f}",
                5.0, Math.toDegrees(rhombohedron.getAngle()), rhombohedron.surfaceArea(), rhombohedron.volume());
        assertEquals(expected, rhombohedron.toString());
    }
}